name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., 1.0.0)"
        required: true
        default: "1.0.0"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Update version in package.json
        if: github.event.inputs.version
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Build app
        run: npm run make
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version && format('v{0}', github.event.inputs.version) || github.ref_name }}
          name: Release ${{ github.event.inputs.version && format('v{0}', github.event.inputs.version) || github.ref_name }}
          body: |
            ## What's New

            ### 🎯 Accountability Features
            - Real-time monitoring of restricted apps and websites
            - Discord notifications for violations
            - Mandatory explanations for all monitoring actions
            - System tray integration with protected quit

            ### 📱 Download Instructions

            **Windows Users:**
            - Download `Not-Enough-Accountability-Setup.exe` for Windows installer
            - Or download `not-enough-accountability-win32-x64.zip` for portable version

            **macOS Users:**
            - Download `Not-Enough-Accountability.dmg` for macOS installer
            - Or download `not-enough-accountability-darwin-x64.zip` for portable version

            ### 🔧 First Time Setup
            1. Install and run the application
            2. Configure your Discord webhook URL (recommended)
            3. Set your work hours (default: 8 AM - 4 PM)
            4. Add restricted apps and keywords
            5. Save settings and start monitoring!

            ### 🆕 Auto-Update
            The app will automatically check for updates and notify you when new versions are available.

            ---

            **Full Changelog:** See the [CHANGELOG.md](CHANGELOG.md) for detailed changes.
          files: |
            ./out/make/**/*
          draft: false
          prerelease: false
